# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
#    title:        Plop CMS
#    description:  Plop CMS - a fully customizable CMS
#    keywords:     plop, cms
#    language:     en
#    robots:       index, follow

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
